version: '3.4'

services:
  aggregatorservice:
    image: ${DOCKER_REGISTRY-}aggregatorservice
    build:
      context: .
      dockerfile: Aggregator/Dockerfile
    ports:
      - "9000:80" 
    depends_on:
      - jaegerservice
      - userservice
      - orderservice
    networks: 
      - backend

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "9004:80"
    depends_on:
      - jaegerservice      
    networks: 
      - backend
 
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "9002:80"
    depends_on:
      - jaegerservice
    networks: 
      - backend
      
  jaegerservice:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks: 
      - backend

networks: 
  backend: 
    driver: bridge