version: '3.4'

services:
  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
  aggregatorservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

